main:
  - name: HOME
    url: ""
    weight: 10

  - name: RESEARCH
    url: research/
    weight: 20

  - name: TEAM
    url: team/
    weight: 30

  - name: PUBLICATIONS
    url: publications/
    weight: 40

  - name: JOIN US
    url: join-us/
    weight: 50
